<?php
    return [
        'MANAGECOMPANY' => 1,
        'COMPANYCUSTOMER' => 2,
        'COMPANYTRANSACTION' => 3,
        'WITHDRAWALREQUEST' => 4,
        'PACKAGES' => 5,
        'INVOICES' => 6,
        'TRANSACTIONS' => 7,
        'MANAGECUSTUMERS' => 8,
        'MYRIDEPAYACCOUNT' => 9,
        'PROFILESETTINGS' => 10,
        'CURRENCY' => 11,
        'ACCOUNTCONFIGURATION' => 12,
        'GENERALSETTINGS' => 13,
        'EMAILCATEGORY' => 14,
        'BRANDEDEMAIL' => 15,
        'EMAILSETTINGS' => 16,
        'EMAILTEMPLATE' => 17,
        'PROFITACCOUNT' => 18,
        'LIABILITIES' => 19,
        'JOURNALENTRIES' => 20,
        'SUPERJOURNAL' => 21,
        'CURRENCYRATE' => 22,
        'WITHDRAWALS' => 23,
        'PAYTABSJSON' => 24,
        'ERROR' => 25,
        'USERROLE' => 26,
        'ROLEPERMISSION' => 27,
        'MANAGEUSER' => 28,
        'SALESTAFF' => 29,
        'VIEW' => 'is_view',
        'ADD' => 'is_add',
        'EDIT' => 'is_edit',
        'STATUS' => 'is_status',
        'DELETE' => 'is_delete',

    ];
?>
